// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/app/bookings/[bookingId]": InferRoute<import("./src/app/app/bookings/[bookingId]/routeType").RouteType>;
    "/app/bookings": InferRoute<import("./src/app/app/bookings/routeType").RouteType>;
  }

  interface StaticRouter {
    "/login": StaticRoute;
    "/signup": StaticRoute;
    "/app/cabins": StaticRoute;
    "/app/dashboard": StaticRoute;
    "/app/settings": StaticRoute;
    "/app/users": StaticRoute;
    "/": StaticRoute;
  }
}
