import { Toaster } from '@/shared/components/ui/sonner';
import { objektiv } from '@/shared/lib/fonts';
import type { Metadata } from 'next';
// @ts-expect-error since TypeScript can't resolve css files
import './globals.css';

import Providers from '@/shared/Providers';
import { Nunito_Sans } from 'next/font/google';
import { type PropsWithChildren } from 'react';

const nunitoSans = Nunito_Sans({ variable: '--font-sans' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en" suppressHydrationWarning className={nunitoSans.variable}>
			<body className={`${objektiv.className}`}>
				<Providers>
					{children}
					<Toaster />

					{/* <ReactQueryDevtools initialIsOpen={false} /> */}
				</Providers>
			</body>
		</html>
	);
}
