import type { Metadata } from 'next';
import './globals.css';
import { raleway } from '@/lib/fonts';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import MainHeader from '@/components/layout/MainHeader';
import SideBar from '@/components/layout/SideBar';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          raleway.className,
          `grid min-h-screen grid-rows-[min-content_1fr_min-content] sm:grid-cols-[minmax(10px,_1fr)_minmax(10px,_4fr)]`,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <MainHeader className="flex items-center justify-between border-b px-4 py-2 text-right dark:border-neutral-600 sm:col-start-2 sm:col-end-2" />
          <SideBar className="flex flex-col p-4 dark:border-neutral-600 sm:col-start-1 sm:col-end-1 sm:row-start-1 sm:row-end-3 sm:border-r" />
          <main className="bg-neutral-100/40 p-4 sm:col-start-2 sm:col-end-2">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
